# Change these first
owner: AndreaTrendafilov # Your GitHub organization or username, where this repository lives
repo: tikvite-uptime # The name of this repository

sites:
  - name: Tikvite
    url: https://tikvite.org
    method: GET
    expectedStatusCodes:
      - 200
      - 403
    __dangerous__disable_verify_peer: true

  - name: Chat
    url: https://chat.tikvite.org
    method: GET
    expectedStatusCodes:
      - 200
      - 403
    __dangerous__disable_verify_peer: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tikvite.org
  # baseUrl: /your-repo-name
  logoUrl: https://status.tikvite.org/logo-192x192.png
  favicon: https://status.tikvite.org/logo-192x192.png
  name: Uptime Tikvite
  navbar:
    - title: Home
      href: https://tikvite.org
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
